[package]
name = "test"
version = "0.0.1"
authors = ["hasezoey <hasezoey@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
diesel = { version = "2.1", features = ["sqlite", "chrono", "returning_clauses_for_sqlite_3_35"] }

[[bin]]
name = "mh"
path = "src.rs"
